name: Build CI Images - Common
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string

      image:
        required: true
        type: string

      tag:
        required: true
        type: string

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build image
        env:
          REPO: ${{ github.repository }}
        run: |
          docker build - < .github/${{ inputs.dockerfile }}.Dockerfile \
            --build-arg SOURCE_IMAGE="${{ inputs.image }}" \
            --build-arg SOURCE_TAG="${{ inputs.tag }}" \
            --tag "ghcr.io/$REPO:ci-${{ inputs.image }}-${{ inputs.tag }}" \
            --label "org.opencontainers.image.source=https://github.com/$REPO" \
            --label "org.opencontainers.image.description=${{ inputs.image }}:${{ inputs.tag }} configured for dotfiles CI"

      - name: login to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          REPO: ${{ github.repository }}
        run: docker push "ghcr.io/$REPO:ci-${{ inputs.image }}-${{ inputs.tag }}"
