name: Build Final Images - Common
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string

      image:
        required: true
        type: string

      tag:
        required: true
        type: string

permissions:
  packages: write

env:
  DOTFILES_OWNER: ${{ github.repository_owner }}
  DOTFILES_REPO: ${{ github.repository }}
  # the DOTFILES_TAG must match the container in the linux build-{distro}-*.yml workflows
  DOTFILES_TAG: ${{ format('ghcr.io/{0}:{1}-{2}', github.repository, inputs.image, inputs.tag) }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build - < .github/${{ inputs.dockerfile }}.Dockerfile \
            --build-arg SOURCE_IMAGE="${{ inputs.image }}" \
            --build-arg SOURCE_TAG="${{ inputs.tag }}" \
            --build-arg OWNER="$DOTFILES_OWNER" \
            --build-arg REPO="$DOTFILES_REPO" \
            --build-arg DEVTOOLS=true \
            --target final \
            --tag "$DOTFILES_TAG" \
            --label "org.opencontainers.image.source=https://github.com/$DOTFILES_REPO" \
            --label "org.opencontainers.image.description=${{ inputs.image }}:${{ inputs.tag }} for $DOTFILES_REPO"

      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image to ghcr.io
        run: docker push "$DOTFILES_TAG"
