name: Build CI
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/Dockerfile'
      - '.github/workflows/build*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  call-build-alpine:
    uses: ./.github/workflows/build-alpine.yml

  call-build-debian:
    uses: ./.github/workflows/build-debian.yml

  call-build-ubuntu:
    uses: ./.github/workflows/build-ubuntu.yml
