name: Build Final Images - Debian, Devuan, and Ubuntu
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-debian-devuan-and-ubuntu
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  call-build-common-debian:
    uses: ./.github/workflows/build-common.yml
    strategy:
      matrix:
        tag: ['sid', 'trixie', 'bookworm', 'bullseye', 'buster']

    with:
      dockerfile: apt
      image: debian
      tag: ${{ matrix.tag }}

  call-build-common-devuan:
    uses: ./.github/workflows/build-common.yml
    strategy:
      matrix:
        tag: ['ceres', 'excalibur', 'daedalus', 'chimaera', 'beowulf']

    with:
      dockerfile: apt
      image: devuan
      tag: ${{ matrix.tag }}

  call-build-common-ubuntu:
    uses: ./.github/workflows/build-common.yml
    strategy:
      matrix:
        tag: ['noble', 'mantic', 'lunar', 'jammy', 'focal']

    with:
      dockerfile: apt
      image: ubuntu
      tag: ${{ matrix.tag }}
