name: Build CI Images - Common
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string

      image:
        required: true
        type: string

      tag:
        required: true
        type: string

permissions:
  packages: write

env:
  DOTFILES_REPO: ${{ github.repository }}
  # the DOTFILES_TAG must match the container in the linux ci-{distro}-*.yml workflows
  DOTFILES_TAG: ${{ format('ghcr.io/{0}:ci-{1}-{2}', github.repository, inputs.image, inputs.tag) }}
  DOTFILES_SHA_TAG: ${{ format('ghcr.io/{0}:ci-{1}-{2}-{3}', github.repository, inputs.image, inputs.tag, github.sha) }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build ci image
        env:
          DOCKER_BUILDKIT: 1

        run: |
          docker build - < .github/${{ inputs.dockerfile }}.Dockerfile \
            --build-arg SOURCE_IMAGE="${{ inputs.image }}" \
            --build-arg SOURCE_TAG="${{ inputs.tag }}" \
            --target ci \
            --tag "$DOTFILES_SHA_TAG" \
            --label "org.opencontainers.image.source=https://github.com/$DOTFILES_REPO" \
            --label "org.opencontainers.image.description=${{ inputs.image }}:${{ inputs.tag }} for $DOTFILES_REPO CI"

      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push ci image to ghcr.io
        run: docker push "$DOTFILES_SHA_TAG"

      - name: tag and push default ci image on main
        if: |
          github.ref_name == 'main'
          && (
            github.event_name == 'push'
            || github.event_name == 'workflow_dispatch'
          )
        run: |
          docker tag "$DOTFILES_SHA_TAG" "$DOTFILES_TAG"
          docker push "$DOTFILES_TAG"
