name: Build Docs
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTFILES_OWNER: ${{ github.repository_owner }}
  DOTFILES_REPO: ${{ github.repository }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      documentation-sources: ${{ steps.filter.outputs.documentation-sources }}
      documentation-targets: ${{ steps.filter.outputs.documentation-targets }}
      documentation-build-defs: ${{ steps.filter.outputs.documentation-build-defs }}
      build-docs: ${{ steps.filter.outputs.build-docs }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: '.github/paths-filter.yml'

  build:
    runs-on: ubuntu-latest
    needs: [paths-filter]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.build-docs == 'true'

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build sphinx
        run: |
          docker build - < .github/docs.Dockerfile \
            --build-arg OWNER="$DOTFILES_OWNER" \
            --build-arg REPO="$DOTFILES_REPO" \
            --target docs \
            --tag "dotfiles:sphinx" \
            --label "org.opencontainers.image.source=https://github.com/$DOTFILES_REPO" \
            --label "org.opencontainers.image.description=sphinx for $DOTFILES_REPO"

      - name: build docs
        run: docker run -v ${{ github.workspace }}/docs:/opt/docs dotfiles:sphinx

      - name: setup-pages
        uses: actions/configure-pages@v5

      - name: upload page artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_build
