name: CI - FreeBSD
run-name: CI / FreeBSD on ${{ github.head_ref || github.ref_name }}
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-freebsd
  cancel-in-progress: true

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: Install and Test on FreeBSD
    strategy:
      matrix:
        release: ['14.0', '13.2', '12.4']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test bundle
        uses: vmactions/freebsd-vm@v1
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          DEBUG: 1
        with:
          release: ${{ matrix.release }}
          envs: "BRANCH"
          prepare: |
            pkg install -y sudo chezmoi

          run: |
            # add ci user
            pw groupadd -n ci
            pw useradd -n ci -g ci -m
            echo 'ci ALL=(ALL) NOPASSWD: ALL' > /usr/local/etc/sudoers.d/ci

            # init chezmoi
            sudo DOTFILES_DEVTOOLS=true -iu ci chezmoi init --apply cjw6k --branch "$BRANCH"

            # confirm installed utils
            sh .github/freebsd/confirm-installed-utils.sh

            # confirm ci user has fish shell
            test `tee </etc/passwd | grep ^ci: | grep -o '[^:]*$'` = `which fish`

            # run tests
            sudo -iu ci fishtape /home/ci/.config/dotfiles/tests.fish
