name: CI - FreeBSD
run-name: CI / FreeBSD on ${{ github.head_ref || github.ref_name }}
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-freebsd
  cancel-in-progress: true

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: Install and Test on FreeBSD
    strategy:
      matrix:
        release: ['14.0']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test bundle
        uses: vmactions/freebsd-vm@v1
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          DEBUG: 1
        with:
          release: ${{ matrix.release }}
          envs: "BRANCH"
          prepare: |
            pkg -d install -y sudo chezmoi

          run: |
            whoami
