name: CI - FreeBSD
run-name: CI / FreeBSD on ${{ github.head_ref || github.ref_name }}
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/freebsd/**'
      - '.github/workflows/ci-freebsd.yml'
      - 'home/private_dot_config/utils.json'
      - 'home/.chezmoiscripts/freebsd/**'
      - 'home/.chezmoiscripts/personal/freebsd/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-freebsd
  cancel-in-progress: true

jobs:
  freebsd:
    runs-on: macos-12
    name: Install and Test on FreeBSD
    strategy:
      matrix:
        release: ['13.1', '13.0', '12.3']

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: test bundle
        uses: vmactions/freebsd-vm@v0
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        with:
          release: ${{ matrix.release }}
          envs: "BRANCH"
          prepare: |
            pkg install -y chezmoi

          run: |
            chezmoi init --apply cjw6k --branch "$BRANCH"
            sh .github/freebsd/confirm-installed-utils.sh
