name: CI - Common
on:
  workflow_call:
    inputs:
      distro:
        required: true
        type: string

      tag:
        required: true
        type: string

      suffix:
        required: false
        type: string
        default: ''

      dotfiles_devtools:
        required: false
        type: boolean
        default: true

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Install and Test on Linux
    # must match env.DOTFILES_TAG in the build-*.yml workflows
    container: ${{ format('ghcr.io/{0}:ci-{1}-{2}{3}', github.repository, inputs.distro, inputs.tag, inputs.suffix) }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: detect distro-and-version-safe command to init dotfiles
        id: init-dotfiles-command
        run: |
          echo command="$(.github/linux/init-dotfiles-command.sh ${{ inputs.distro }} ${{ inputs.tag }})" \
            >> "$GITHUB_OUTPUT"

      - name: init dotfiles
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          DOTFILES_DEVTOOLS: ${{ inputs.dotfiles_devtools }}
        run: sudo -Eiu ci ${{ steps.init-dotfiles-command.outputs.command}} --branch "$BRANCH"

      - name: verify utilities are present
        run: .github/linux/confirm-installed-utils.sh "${{ inputs.distro }}" "${{ inputs.tag }}"

      - name: verify ci user has fish-shell
        run: |
          test "$(tee </etc/passwd | grep ^ci: | grep -o '[^:]*$')" = "$(which fish)"

      - name: run tests
        run: sudo -iu ci fishtape /home/ci/.config/dotfiles/tests.fish
