name: CI - Ubuntu
run-name: CI / Linux / Ubuntu on ${{ github.head_ref || github.ref_name }}
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      suffix:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ubuntu
  cancel-in-progress: true

jobs:
  call-common-linux:
    uses: ./.github/workflows/ci-linux-common.yml
    strategy:
      matrix:
        tag: ['latest', 'kinetic', 'jammy', 'focal', 'bionic', 'xenial']

    with:
      distro: ubuntu
      tag: ${{ matrix.tag }}
      suffix: ${{ inputs.suffix }}
