name: Continuous Integration - Alpine
run-name: CI / Linux / Alpine on ${{ github.ref_name }}
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

    paths:
      - '.github/linux/**'
      - '.github/workflows/ci-linux-common.yml'
      - '.github/workflows/ci-linux-alpine.yml'
      - 'home/private_dot_config/utils.json'
      - 'home/.chezmoiscripts/linux/*.sh'
      - 'home/.chezmoiscripts/linux/*.sh.tmpl'
      - 'home/.chezmoiscripts/linux/alpine/**'
      - 'home/.chezmoiscripts/personal/linux/*.sh'
      - 'home/.chezmoiscripts/personal/linux/*.sh.tmpl'
      - 'home/.chezmoiscripts/personal/linux/alpine/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-common-linux:
    uses: ./.github/workflows/ci-linux-common.yml
    strategy:
      matrix:
        - tag: ['edge', '3.17']

    with:
      distro: alpine
      tag: ${{ matrix.tag }}
