name: CI - Windows
run-name: CI / Windows on ${{ github.head_ref || github.ref_name }}
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-windows
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    name: Install and Test on Windows
    env:
      BRANCH: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup profile
        run: |
          if ( -not (Test-Path $PROFILE) ) {
            New-Item -Path $PROFILE -Type File -Force
          }
          Get-ChildItem '.github/windows/profile/' -File `
            | Select-Object -ExpandProperty Fullname `
            | Foreach-Object -Process {Add-Content $PROFILE "Import-Module $_"}

      - name: restore scoop cache
        uses: actions/cache@v4
        env:
          cache-name: cache-scoop-assets

        with:
          path: ~/scoop/cache/
          key: ${{ env.cache-name }}-${{ github.run_id }}
          restore-keys:
            ${{ env.cache-name }}-

      - name: install scoop
        run: |
          Install-Scoop
          scoop --version

      - name: scoop checkup
        run: scoop checkup

      - name: install chezmoi
        run: scoop install chezmoi

      - name: init dotfiles
        env:
          DOTFILES_DEVTOOLS: true
          DOTFILES_DEVTOOLS_C: false
          DOTFILES_DEVTOOLS_DOCKER: false
          DOTFILES_DEVTOOLS_EXTRA: false
          DOTFILES_DEVTOOLS_GO: false
          DOTFILES_DEVTOOLS_HASKELL: false
          DOTFILES_DEVTOOLS_JS: false
          DOTFILES_DEVTOOLS_K8S: false
          DOTFILES_DEVTOOLS_LUA: false
          DOTFILES_DEVTOOLS_PHP: false
        run: chezmoi init --apply cjw6k --branch "$env:BRANCH"

      - name: scoop list
        run: scoop list

      - name: verify utilities are present
        run: Confirm-InstalledUtils
