name: Continuous Integration - Windows
run-name: CI / Windows on ${{ github.ref_name }}
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

    paths:
      - '.github/windows/**'
      - '.github/workflows/ci-windows.yml'
      - 'home/private_dot_config/utils.json'
      - 'home/.chezmoiscripts/windows/**'
      - 'home/.chezmoiscripts/personal/windows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    name: Install and Test on Windows
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup profile
        run: |
          if ( -not (Test-Path $PROFILE) ) {
            New-Item -Path $PROFILE -Type File -Force
          }
          Get-ChildItem '.github/windows/profile/' -File `
            | Select-Object -ExpandProperty Fullname `
            | Foreach-Object -Process {Add-Content $PROFILE "Import-Module $_"}

      - name: restore shovel cache
        uses: actions/cache@v3
        env:
          cache-name: cache-shovel-assets

        with:
          path: ~/scoop/cache/
          key: ${{ env.cache-name }}-${{ github.run_id }}
          restore-keys:
            ${{ env.cache-name }}-

      - name: install shovel
        run: |
          Install-Shovel
          shovel --version

      - name: shovel checkup
        run: shovel checkup

      - name: install chezmoi
        run: shovel install chezmoi

      - name: init dotfiles
        run: chezmoi init cjw6k --apply --branch ${{ github.ref_name }}

      - name: shovel list
        run: shovel list

      - name: verify utilities are present
        run: Confirm-InstalledUtils
