name: Continuous Integration

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.pull_request.url || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    name: Install and Test on Windows
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup profile
        run: |
          if ( -not (Test-Path $PROFILE) ) {
            New-Item -Path $PROFILE -Type File -Force
          }
          Get-ChildItem '.github/windows/profile/' -File `
            | Select-Object -ExpandProperty Fullname `
            | Foreach-Object -Process {Add-Content $PROFILE "Import-Module $_"}

      - name: restore shovel cache
        uses: actions/cache@v3
        env:
          cache-name: cache-shovel-assets
        with:
          path: ~/scoop/cache/
          key: ${{ env.cache-name }}-${{ github.run_id }}
          restore-keys:
            ${{ env.cache-name }}-

      - name: install shovel
        run: |
          Install-Shovel
          shovel --version

      - name: shovel checkup
        run: shovel checkup

      - name: install chezmoi
        run: shovel install chezmoi

      - name: init dotfiles
        run: chezmoi init cjw6k --apply --branch ${{ github.ref_name }}

      - name: shovel list
        run: shovel list

      - name: verify utilities are present
        run: Confirm-InstalledUtils

  alpine:
    # todo: matrix of branches for current releases, see https://alpinelinux.org/releases/
    runs-on: ubuntu-latest
    name: Install and Test on Alpine
    strategy:
      matrix:
        branch: [edge, v3.17, v3.16, v3.15, v3.14]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: ${{ matrix.branch }}

      - name: install chezmoi
        shell: alpine.sh --root {0}
        run: apk add chezmoi

      - name: detect version-safe command to init dotfiles
        id: init-dotfiles-command
        run: echo command="$(.github/linux/init-dotfiles-command.sh alpine ${{ matrix.branch }})" >> $GITHUB_OUTPUT

      - name: init dotfiles
        shell: alpine.sh --root {0}
        # modern install: chezmoi init --apply cjw6k --branch ...
        run: ${{ steps.init-dotfiles-command.outputs.command}} --branch ${{ github.ref_name }}

      - name: verify utilities are present
        shell: alpine.sh --root {0}
        run: .github/linux/confirm-installed-utils.sh
