name: Continuous Integration

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-linux-alpine:
    uses: cjw6k/dotfiles/.github/workflows/ci-linux-alpine.yml

  call-freebsd:
    needs: call-linux-alpine
    uses: cjw6k/dotfiles/.github/workflows/ci-freebsd.yml

  call-windows:
    needs: call-linux-alpine
    uses: cjw6k/dotfiles/.github/workflows/ci-windows.yml

  call-linux-gentoo:
    needs: call-linux-alpine
    uses: cjw6k/dotfiles/.github/workflows/ci-linux-gentoo.yml

  call-linux-debian:
    needs: call-linux-alpine
    uses: cjw6k/dotfiles/.github/workflows/ci-linux-debian.yml

  call-linux-ubuntu:
    needs: call-linux-alpine
    uses: cjw6k/dotfiles/.github/workflows/ci-linux-ubuntu.yml
