name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      ci-build-alpine: ${{ steps.filter.outputs.ci-build-alpine }}
      ci-build-debian: ${{ steps.filter.outputs.ci-build-debian }}
      ci-build-devuan: ${{ steps.filter.outputs.ci-build-devuan }}
      ci-build-ubuntu: ${{ steps.filter.outputs.ci-build-ubuntu }}
      ci-freebsd: ${{ steps.filter.outputs.ci-freebsd }}
      ci-debian: ${{ steps.filter.outputs.ci-debian }}
      ci-devuan: ${{ steps.filter.outputs.ci-devuan }}
      ci-gentoo: ${{ steps.filter.outputs.ci-gentoo }}
      ci-ubuntu: ${{ steps.filter.outputs.ci-ubuntu }}
      ci-windows: ${{ steps.filter.outputs.ci-windows }}
      ci-any: ${{ steps.filter.outputs.ci-any }}
      dotfiles-sources: ${{ steps.filter.outputs.dotfiles-sources }}
      build-alpine: ${{ steps.filter.outputs.build-alpine }}
      build-debian-devuan-and-ubuntu: ${{ steps.filter.outputs.build-debian-devuan-and-ubuntu }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: '.github/paths-filter.yml'

  ci-build-alpine:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.ci-build-alpine == 'true' }}
    uses: ./.github/workflows/ci-build-alpine.yml
    permissions:
      packages: write

  ci-build-debian:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.ci-build-debian == 'true' }}
    uses: ./.github/workflows/ci-build-debian.yml
    permissions:
      packages: write

  ci-build-devuan:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.ci-build-devuan == 'true' }}
    uses: ./.github/workflows/ci-build-devuan.yml
    permissions:
      packages: write

  ci-build-ubuntu:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.ci-build-ubuntu == 'true' }}
    uses: ./.github/workflows/ci-build-ubuntu.yml
    permissions:
      packages: write

  # alpine completes very quickly, if it doesn't pass skip the others
  ci-alpine:
    needs: [paths-filter, ci-build-alpine]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-any == 'true'

    uses: ./.github/workflows/ci-linux-alpine.yml
    with:
      suffix: ${{ needs.paths-filter.outputs.ci-build-alpine == 'true' && format('-{0}', github.sha) || '' }}

  ci-freebsd:
    needs: [paths-filter, ci-alpine]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-freebsd == 'true'

    uses: ./.github/workflows/ci-freebsd.yml

  ci-debian:
    needs: [paths-filter, ci-alpine, ci-build-debian]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-debian == 'true'

    uses: ./.github/workflows/ci-linux-debian.yml
    with:
      suffix: ${{ needs.paths-filter.outputs.ci-build-debian == 'true' && format('-{0}', github.sha) || ''}}

  ci-devuan:
    needs: [paths-filter, ci-alpine, ci-build-devuan]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-devuan == 'true'

    uses: ./.github/workflows/ci-linux-devuan.yml
    with:
      suffix: ${{ needs.paths-filter.outputs.ci-build-devuan == 'true' && format('-{0}', github.sha) || ''}}

  ci-gentoo:
    needs: [paths-filter, ci-alpine]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-gentoo == 'true'

    uses: ./.github/workflows/ci-linux-gentoo.yml
    secrets:
      CI_GPG_KEY: ${{ secrets.CI_GPG_KEY }}
      CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}


  ci-ubuntu:
    needs: [paths-filter, ci-alpine, ci-build-ubuntu]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-ubuntu == 'true'

    uses: ./.github/workflows/ci-linux-ubuntu.yml
    with:
      suffix: ${{ needs.paths-filter.outputs.ci-build-ubuntu == 'true' && format('-{0}', github.sha) || ''}}

  ci-windows:
    needs: [paths-filter, ci-alpine]
    if: |
      !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.ci-windows == 'true'

    uses: ./.github/workflows/ci-windows.yml

  build-alpine:
    needs: [paths-filter, ci-alpine]
    if: |
      github.event_name == 'push'
      && github.ref_name == 'main'
      && !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.build-alpine == 'true'

    uses: ./.github/workflows/build-alpine.yml
    permissions:
      packages: write

  build-debian-devuan-and-ubuntu:
    needs: [paths-filter, ci-debian, ci-devuan, ci-ubuntu]
    if: |
      github.event_name == 'push'
      && github.ref_name == 'main'
      && !cancelled()
      && !contains(needs.*.result, 'failed')
      && !contains(needs.*.result, 'cancelled')
      && needs.paths-filter.outputs.build-debian-devuan-and-ubuntu == 'true'

    uses: ./.github/workflows/build-debian-devuan-and-ubuntu.yml
    permissions:
      packages: write
